#!/usr/bin/env fish


function bupit
    set -l dir "$argv"


    if test -d "$dir"
        set -x BUP_DIR "$dir"/(hostname)


        bup init
        and bup index "/home/$USER"
        and bup save -n (hostname)-home-"$USER" "/home/$USER"
        and bup fsck -g
    else
        echo "Not available: $dir"
    end
end


bupit /run/media/david/odysseus1
bupit /run/media/david/odysseus2
bupit /run/media/david/odysseus3
