#!/usr/bin/env zsh
# set new bg

if [[ -z $1 ]]; then
    feh --bg-scale ~/Pictures/wallpapers/bg-`hostname`-0  ~/Pictures/wallpapers/bg-`hostname`-1
    exit
fi

if [[ $1 == "-h" ]]; then
    echo "Usage: bg-set [options]"
    echo "    bg-set path/to/file [n]    sets file as wallpaper of screen n (default: 0)"
    echo "    bg-set -r n                reverts the wallpaper of screen n"
    echo "    bg-set -s                  swaps the wallpapers on two screens"
    exit
fi

if [[ $1 == "-r" ]]; then
    mv ~/Pictures/wallpapers/bg-`hostname`-$2 ~/Pictures/wallpapers/bg-`hostname`-$2-tmp
    mv ~/Pictures/wallpapers/bg-`hostname`-$2-old ~/Pictures/wallpapers/bg-`hostname`-$2
    mv ~/Pictures/wallpapers/bg-`hostname`-$2-tmp ~/Pictures/wallpapers/bg-`hostname`-$2-old
    feh --bg-scale ~/Pictures/wallpapers/bg-`hostname`-0  ~/Pictures/wallpapers/bg-`hostname`-1
elif [[ $1 == "-s" ]]; then
    feh --bg-scale ~/Pictures/wallpapers/bg-`hostname`-1  ~/Pictures/wallpapers/bg-`hostname`-0
    mv ~/Pictures/wallpapers/bg-`hostname`-0 ~/Pictures/wallpapers/bg-`hostname`-0-tmp
    mv ~/Pictures/wallpapers/bg-`hostname`-1 ~/Pictures/wallpapers/bg-`hostname`-0
    mv ~/Pictures/wallpapers/bg-`hostname`-0-tmp ~/Pictures/wallpapers/bg-`hostname`-1
elif [[ -z $2 ]]; then
    mv ~/Pictures/wallpapers/bg-`hostname`-0 ~/Pictures/wallpapers/bg-`hostname`-0-old
    ln -s $1 ~/Pictures/wallpapers/bg-`hostname`-0
    feh --bg-scale ~/Pictures/wallpapers/bg-`hostname`-0  ~/Pictures/wallpapers/bg-`hostname`-1
else
    mv ~/Pictures/wallpapers/bg-`hostname`-$2 ~/Pictures/wallpapers/bg-`hostname`-$2-old
    ln -s $1 ~/Pictures/wallpapers/bg-`hostname`-$2
    feh --bg-scale ~/Pictures/wallpapers/bg-`hostname`-0  ~/Pictures/wallpapers/bg-`hostname`-1
fi

