#!/usr/bin/env python

import re
from subprocess import Popen, PIPE
import sys

proc = Popen(["bluetoothctl", "devices"], stdout=PIPE, stderr=PIPE)
stdout, stderr = proc.communicate()
stdout = stdout.decode().strip()
stdout = stdout.split("\n")


def parse_address_name(line):
    address, name = re.sub(r"Device ([^ ]*) (.*)", (r"\1#\2"), line).split("#")
    return name, address


devs = dict([
    parse_address_name(line) for line in stdout if line
])
print(devs)

disconnect = "Disconnect\n"

proc = Popen(["dmenu"] + sys.argv[1:], stdin=PIPE, stdout=PIPE, stderr=PIPE)
options = ("\n".join(list(devs.keys()) + [disconnect])).encode()
stdout, stderr = proc.communicate(input=options)
choice = stdout.decode().strip()

if choice == disconnect.strip():
    for addr in devs.values():
        proc = Popen(["bluetoothctl", "disconnect", addr])
        proc.communicate()
else:
    proc = Popen(["bluetoothctl", "connect", devs[choice]])
    proc.communicate()
