#!/usr/bin/env fish


# Create a temporary file.
set fname_temp (mktemp)
# echo "# " > $fname_temp

# Open the temporary file with `editor` (note that since we do not add
# `--no-wait` this is a sync operation).
editor $fname_temp
# TODO Go into insert mode right away
# editor -e "(progn (find-file \"$fname_temp\") (evil-insert))"

# Append the contents of the temporary file to `Inbox.md`.
echo >> Inbox.md
echo >> Inbox.md
cat $fname_temp >> Inbox.md

# Delete the temporary file.
command rm $fname_temp
