#!/usr/bin/env zsh
# Clean up the $HOME directory (moving anything not belonging there to
# $HOME/Temporary).

# TODO someday do something like this instead?
# $(grep --no-filename --color -i -E '^\[.*\]' \
#        .mrconfig \
#        .git.mrconfig \
#        .gitlab.mrconfig \
#        .private.mrconfig \
#       | sed -r 's/\[(.*)\]/\1/' | paste -d ' ' -s) )
allowed=( Bilder \
          Bin \
          Buchhaltung \
          Code \
          Dokumente \
          In.org \
          Kalender \
          LaTeX \
          Lehre \
          Lehrstuhl \
          Literatur \
          Mail \
          NixOS \
          Projekte \
          Screencasts \
          Spiele \
          Templates \
          Temporary \
          texmf \
          TODO.org \
          TODO.org_archive \
          VMs \
          Vorträge )
temporary=Temporary

currentDir=$(pwd)
cd $HOME

IFS=$'\n'
for f in $(ls); do
    if [[ ${allowed[(i)$f]} -gt $#allowed ]]; then
        cd $temporary
        if [[ -e "$f" ]]; then
            printf "Archiving older versions of $f… "
            archiveFilename=$(mktemp -u -d -p . "$f-XXXXX")
            mv "$f" "$archiveFilename" 2&> /dev/null
        fi
        cd $HOME

        print "Cleaning $f"
        mv "$f" "$temporary"
    fi
done

cd "$currentDir"
