#!/usr/bin/env zsh
# Clean up the $HOME directory (moving anything not belonging there to
# $HOME/Temporary).


echo 'This script was replaced by `wf clean` (see NixOS config).'


exit 1


set -e


allowed=( Bilder \
          Bin \
          Buchhaltung \
          Code \
          Day.md \
          Dokumente \
          Drucken \
          In.org \
          Inbox \
          Kalender \
          LaTeX \
          Lehre \
          Lehrstuhl \
          Literatur \
          Mail \
          Musik \
          NixOS \
          prolcs \
          Projekte \
          Screencasts \
          Spiele \
          Studenten \
          Templates \
          Temporary \
          texmf \
          TODO.org \
          TODO.org_archive \
          VMs \
          Vorträge \
          Zettels \
          Zettels_ )
temporary=Temporary
inbox=Inbox


currentDir=$(pwd)
cd $HOME


IFS=$'\n'
for f in $(ls); do
    if [[ ${allowed[(i)$f]} -gt $#allowed ]]; then
        cd $inbox
        if [[ -e "$f" ]]; then
            printf "Archiving older versions of $f… "
            archiveFilename=$(mktemp -u -d -p . "$f-XXXXX")
            mv "$f" "$archiveFilename" 2&> /dev/null
        fi
        cd $HOME
        print "Cleaning $f"
        mv "$f" "$inbox"
    fi
done


cd "$currentDir"
