#!/usr/bin/env sh

applications="telegram-desktop"

IFS='
'
for a in $applications; do
    if pgrep -f "$a" >> /dev/null; then
        killall -HUP "$a"
        echo "Killed $a"
    fi
done


volume mute
