#!/usr/bin/env fish


function fixfonts
    for f in $argv
        set tmp (mktemp)
        gs -o "$tmp" -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -dEmbedAllFonts=true "$f"
        mv "$tmp" "$f"
    end
end


fixfonts $argv
