#!/usr/bin/env zsh
#
# Fixes or sets up remotes for my external hard drives, pen drives etc.

set -e

dir=$(realpath --relative-to $HOME $(pwd))

typeset -A remotes
remotes=( seagate "/run/media/$USER/SEAGATE-MWQ/$dir"
          zeno    "/run/media/$USER/ZENO/$dir" )

function inAnnex {
    git annex status &> /dev/null
}

function fixRemote {
    name=$1
    url=$2

    if [[ ! $(git remote get-url $name 2> /dev/null) == $url ]]; then
        if git remote add $name "$url" &> /dev/null; then
            echo "Added remote $name at $url"
        elif git remote set-url $name "$url" &> /dev/null; then
            echo "Reset remote $name to url $url"
        else
            echo "Could not fix remote $name at $url"
        fi
    fi
}

function fixRemotes {
    for k in "${(@k)remotes}"; do
        if inAnnex; then
            remotePath="$remotes[$k]"
        else
            remotePath="$remotes[$k].git"
        fi

        fixRemote $k $remotePath
    done
}

fixRemotes
