#!/usr/bin/env bash
# show own global ip

site=http://checkip.dyndns.org

if (ping -c 1 $site 2&> /dev/null); then
  echo "???"
else
  wget $site -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>' | head -1
fi
