#!/usr/bin/env fish
#
# Required: curl, pdftotext (from poppler-utils), cat, grep, sed


if test "X$argv" = "X--help" -o "X$argv" = "X-h"
    echo "Usage: justika [-i] [-w] [-a] [-h]"
    printf "%s\n" \
        "|-i, --pdfinfo|Print pdfinfo" \
        "|-w, --week|Print all offers of the current week" \
        "|-a, --all|Print all offers (not just the vegetarian one)" \
        "|-n, --next|Print next week's offers instead of the current week's" \
        | column -t -s "|"
    echo "Without arguments, print today's offer"
    exit 0
end


set -l week
set -l all
set -l info
set -l next
for arg in $argv
    if test "X$arg" = "X--week" -o "X$arg" = "X-w"
        set week t
    else if test "X$arg" = "X--pdfinfo" -o "X$arg" = "X-i"
        set info t
    else if test "X$arg" = "X--all" -o "X$arg" = "X-a"
        set all t
    else if test "X$arg" = "X--next" -o "X$arg" = "X-n"
        set next t
    end
end


set dir "$HOME/.justika/"
mkdir "$dir" 2> /dev/null


if test "X$next" = "X"
    set name "$dir/"(date +%V)
else
    set name "$dir/"(math (date +%V) + 1)
end
set pdf "$name".pdf
set txt "$name".txt


if test ! -f "$pdf"
    if test "X$next" = "X"
        curl --silent --output "$pdf" http://justika.de/Speisekarten/Justika_Wochenkarte_aktuell.pdf
    else
        curl --silent --output "$pdf" http://justika.de/Speisekarten/Justika_Wochenkarte_kommend.pdf
    end
end


if file "$pdf" | grep PDF > /dev/null


    pdftotext "$pdf" "$txt"


    set days '(Montag|Dienstag|Mittwoch|Donnerstag|Freitag|Samstag|Sonntag)'


    set -l IFS
    set content (cat "$txt" \
    # discard heading
    | grep -v 'Kalenderwoche' \
    # discard footer
    | sed -rn '/Täglich wechselnde Suppe/q;p' \
    # discard ingredients footnotes and prices
    | sed -r "/$days/n;s/([[:digit:]],?)+( €)?//g" \
    # enclose OPTIMAHL in brackets
    | sed -r "s/\"(OPTIMAHL)\"/(\1™)/" \
    # discard empty lines
    | grep -v '^ *$' \
    # if OPTIMAHL is on its own line, move it up to the previous line
    | tr '\n' '#' \
    | sed -r "s/#(\(OPTIMAHL[^#]*#)/ \1/g" \
    | tr '#' '\n' \
    # add bullet points
    | sed -r "/$days/n;s/^/• /")


    if test "X$week" = "X" -a "X$next" = "X"
        set -x LANG de_DE.UTF-8
        if test "X$all" = "X"
            echo "$content" | grep --color=never -A 1 (date +%A)
        else
            echo "$content" | grep --color=never -A 3 (date +%A)
        end
    else
        if test "X$all" = "X"
            echo "$content" | grep --color=never -A 1 -E "^[^•]" | grep -v -E "^--"
        else
            echo "$content"
        end
    end
    if test -n "$info"
        pdfinfo "$pdf"
    end


else


    echo "PDF file could not be downloaded"


end
