#!/usr/bin/env zsh
#
# phone - Diverse utilities for my Nexus 5X.
#
# Copyright ⓒ 2017-∞ David Pätzel
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -euo pipefail


# unneeded if proper udev rules are set up
function fixADB {
    if adb kill-server; then
        sudo adb start-server
    else
        adb devices
    fi
}


function getPhotos {
    for storage in self/primary 3337-3432; do
        dir=$(mktemp --dry-run --directory --tmpdir=. $(date -I)-photos-XXXX)

        echo "Starting pull of $dir DCIM camera folder …"
        adb pull /storage/$storage/DCIM/Camera $dir

        if [[ -z $(ls "$dir") ]]; then
            echo "No photos to archive"
            rm -rf "$dir"
        else
            if adb shell "test -d /storage/$storage/DCIM/Archive"; then
                echo "Archive directory already existed, appending …"
            elif adb shell "test \! -e /storage/$storage/DCIM/Archive"; then
                echo "Archive directory did not exist, creating …"
                adb shell "mkdir /storage/$storage/DCIM/Archive/"
            else
                echo "Archive is not a directory, aborting!"
                return 1
            fi
            echo "Archiving photos on phone…"
            adb shell "mv /storage/$storage/DCIM/Camera/* /storage/$storage/DCIM/Archive/"
        fi

        echo "Removing local thumbnails …"
        rm "$dir"/thumbnails &> /dev/null || true
    done
}


function getRecordings {
    what=recordings
    localDir=$(mktemp --dry-run --directory --tmpdir=. $(date -I)-$what-XXXX)
    phoneDir=sdcard/Android/data/com.github.axet.audiorecorder/files/recordings

    adb pull "$phoneDir" "$localDir"

    if [[ -z $(ls $localDir) ]]; then
        echo "No $what to archive"
        rm -rf $localDir
    else
        if adb shell "test -d $phoneDir/../Archive"; then
            echo Archive directory already existed, appending
        elif adb shell "test \! -e $phoneDir/../Archive"; then
            echo Archive directory did not exist, creating
            adb shell "mkdir $phoneDir/../Archive/"
        else
            echo Archive is not a directory, aborting!
            return 1
        fi
        echo "Archiving $what on phone…"
        adb shell "mv $phoneDir/* $phoneDir/../Archive/"
    fi
}


case $1 in
    photos)
        getPhotos
        ;;
    recordings)
        getRecordings
        ;;
    fixadb)
        fixADB
        ;;
esac
