#!/usr/bin/env sh


profile=$1


printf "Stopping conky… "
killall conky -9 2> /dev/null
if [[ $? -eq 0 ]]; then
    echo "stopped."
else
    echo "not stopped (was it running?)."
fi


sleep 0.5

if [[ -z $profile ]]; then
    file=$HOME/.conkyrc
else
    file=$HOME/.conkyrc-$profile
fi
echo "Running conky -c $file"
conky -c $file &> /dev/null
