#!/usr/bin/env bash
#
# Screen layout switcher.  Sometimes I want to use an external screen.


resetWM() {
    killall compton

    "$HOME"/.fehbg

    killall dzen2

    xmonad --restart

    compton -b
}


case $1 in
    work | w)
        case $2 in
            mobile | m)
                # TODO should probably differentiate between hostnames here (e.g. this is only possible for sokrates)
                xrandr \
                    --output VIRTUAL1 --off \
                    --output eDP-1 --primary --mode 1920x1080 --pos 0x900 --rotate normal \
                    --output DP-1 --off \
                    --output DP-2-1 --off \
                    --output DP-2-2 --off \
                    --output DP-2-3 --off \
                    --output HDMI-2 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off
                resetWM
                reconky mobile
                ;;
            home1 | h1)
                xrandr \
                   --output VIRTUAL1 --off \
                   --output eDP-1 --primary --mode 1920x1080 --pos 0x900 --rotate normal \
                   --output DP-1 --mode 1920x1080 --pos 1920x0 --rotate normal \
                   --output DP-2-1 --off \
                   --output DP-2-2 --off \
                   --output DP-2-3 --off \
                   --output HDMI-2 --off \
                   --output HDMI-1 --off \
                   --output DP-2 --off
                resetWM
                reconky home1
                ;;
            home2 | h2)
                xrandr \
                    --output VIRTUAL1 --off \
                    --output eDP-1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal \
                    --output DP1 --off \
                    --output DP-2-1 --off \
                    --output DP-2-2 --off \
                    --output DP-2-3 --off \
                    --output HDMI-2 --mode 1920x1080 --pos 0x0 --rotate normal \
                    --output HDMI-1 --off \
                    --output DP-2 --off
                resetWM
                reconky home2
                ;;
            docked | d | *)
                xrandr \
                   --output VIRTUAL1 --off \
                   --output eDP-1 --primary --mode 1920x1080 --pos 0x180 --rotate normal \
                   --output DP-1 --off \
                   --output DP-2-1 --mode 2560x1440 --pos 1920x0 --rotate normal \
                   --output DP-2-2 --off \
                   --output DP-2-3 --off \
                   --output HDMI-2 --off \
                   --output HDMI-1 --off \
                   --output DP-2 --off
                resetWM
                reconky docked
                ;;
        esac
        ;;

    *)
        echo "Select a setup: {work {single,home,docked,}}"
esac
