#!/usr/bin/env bash
#
# Screen layout switcher.  Sometimes I want to use an external screen.


resetWM() {
    "$HOME"/.fehbg

    killall dzen2

    xmonad --restart
}


case $1 in
    home | h)
        resetWM
        reconky home1
        ;;
    work | w)
        case $2 in
            mobile | m)
                # TODO should probably differentiate between hostnames here (e.g. this is only possible for sokrates)
                xrandr \
                    --output eDP-1 --primary --mode 1920x1080 --pos 0x900 --rotate normal \
                    --output DP-1 --off \
                    --output DP-2-1 --off \
                    --output DP-2-2 --off \
                    --output DP-2-3 --off \
                    --output HDMI-2 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off
                resetWM
                reconky mobile
                ;;
            home | h )
                xrandr \
                    --output eDP-1 --primary --mode 1920x1080 --pos 1920x256 --rotate normal \
                    --output DP-1 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off \
                    --output HDMI-2 --mode 1920x1080 --pos 0x0 --rotate normal \
                    --output DP-2-1 --off \
                    --output DP-2-2 --off \
                    --output DP-2-3 --off
                resetWM
                resetWM
                reconky home
                ;;
            home1 | h1)
                xrandr \
                   --output eDP-1 --primary --mode 1920x1080 --pos 0x900 --rotate normal \
                   --output DP-1 --mode 1920x1080 --pos 1920x0 --rotate normal \
                   --output DP-2-1 --off \
                   --output DP-2-2 --off \
                   --output DP-2-3 --off \
                   --output HDMI-2 --off \
                   --output HDMI-1 --off \
                   --output DP-2 --off
                resetWM
                reconky home1
                ;;
            home2 | h2)
                xrandr \
                    --output eDP-1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal \
                    --output DP1 --off \
                    --output DP-2-1 --off \
                    --output DP-2-2 --off \
                    --output DP-2-3 --off \
                    --output HDMI-2 --mode 1920x1080 --pos 0x0 --rotate normal \
                    --output HDMI-1 --off \
                    --output DP-2 --off
                resetWM
                reconky home2
                ;;
            home3 | h3)
                xrandr \
                    --output eDP-1 --primary --mode 1920x1080 --pos 2560x1080 --rotate normal \
                    --output DP-1 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off \
                    --output HDMI-2 --mode 2560x1440 --pos 0x0 --rotate normal
                resetWM
                reconky home3
                ;;
            dockedhome1 | dh1)
                xrandr \
                    --output eDP-1 --off \
                    --output DP-1 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off \
                    --output HDMI-2 --off \
                    --output DP-2-1 --off \
                    --output DP-2-2 --primary --mode 2560x1440 --pos 0x0 --rotate normal \
                    --output DP-2-3 --off
                resetWM
                reconky dockedhome1
                ;;
            dockedhome | dh)
                xrandr \
                    --output eDP-1 --primary --mode 1920x1080 --pos 2560x0 --rotate normal \
                    --output DP-1 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off \
                    --output HDMI-2 --off \
                    --output DP-2-2 --mode 2560x1440 --pos 0x0 --rotate normal \
                    --output DP-2-1 --off \
                    --output DP-2-3 --off
                resetWM
                reconky dockedhome
                ;;
            docked1 | d1)
                # strange: this does sometimes not work if using only one call to xrandr
                xrandr \
                    --output eDP-1 --off \
                    --output DP-1 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off \
                    --output HDMI-2 --off \
                    --output DP-2-1 --mode 2560x1440 --pos 0x0 --rotate normal \
                    --output DP-2-2 --mode 2560x1440 --pos 2560x0 --rotate normal \
                    --output DP-2-3 --off
                resetWM
                reconky docked
                ;;
            work | w)
                xrandr \
                    --output eDP-1 --off \
                    --output DP-1 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off \
                    --output HDMI-2 --mode 2560x1440 --pos 0x0 --rotate normal \
                    --output DP-2-1 --off \
                    --output DP-2-2 --off \
                    --output DP-2-3 --off
                resetWM
                reconky dockedhome1
                ;;
            docked | d | *)
                xrandr \
                    --output eDP-1 --off \
                    --output DP-1 --off \
                    --output HDMI-1 --off \
                    --output DP-2 --off \
                    --output HDMI-2 --off \
                    --output DP-2-1 --mode 2560x1440 --pos 0x0 --rotate right \
                    --output DP-2-2 --mode 2560x1440 --pos 1440x800 --rotate normal \
                    --output DP-2-3 --off
                # xrandr --verbose --output DP-1 --off
                # xrandr --verbose --output DP-2 --off
                # xrandr --verbose --output DP-2-1 --off
                # xrandr --verbose --output DP-2-2 --off
                # xrandr --verbose --output DP-2-3 --off
                # xrandr --verbose --output eDP-1 --off
                # xrandr --verbose --output HDMI-1 --off
                # xrandr --verbose --output HDMI-2 --off
                # xrandr --verbose --output DP-2-1 --mode 2560x1440 --pos 0x0 --rotate right --crtc 1
                # xrandr --verbose --output DP-2-2 --mode 2560x1440 --pos 1440x800 --rotate normal --crtc 1
                # xrandr --output DP-2-3 --off
                resetWM
                resetWM
                reconky docked
                ;;
        esac
        ;;

    *)
        echo "Select a setup: {work {single,home,docked,}}"
esac
