#!/usr/bin/env sh
#
# Screen layout switcher.  Sometimes I want to use an external screen.


function resetWM {
    killall compton

    $HOME/.fehbg

    killall dzen2

    xmonad --restart

    compton -b
}


case $1 in
    home)
        xrandr --output HDMI1 --off --output LVDS1 --mode 1366x768 --pos 0x312 --rotate normal --output VIRTUAL1 --off --output DP1 --off --output VGA1 --mode 1920x1080 --pos 1366x0 --rotate normal
        resetWM
        reconky dual
        ;;
    tv)
        xrandr --output HDMI1 --mode 1920x1080 --output LVDS1 --mode 1366x768 --pos 0x312 --rotate normal --output VIRTUAL1 --off --output DP1 --off --output VGA1 --off
        resetWM
        reconky
        ;;
    work)
        case $2 in
            single)
                # TODO should probably differentiate between hostnames here (e.g. this is only possible for sokrates)
                xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1920x1080 --pos 0x900 --rotate normal --output DP1 --off --output DP2-1 --off --output DP2-2 --off --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
                resetWM
                reconky
                ;;
            home)
                xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1920x1080 --pos 0x900 --rotate normal --output DP1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP2-1 --off --output DP2-2 --off --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
                resetWM
                reconky homework
                ;;
            *)
                xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1920x1080 --pos 0x900 --rotate normal --output DP1 --off --output DP2-1 --mode 2560x1440 --pos 1920x0 --rotate normal --output DP2-2 --off --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
                resetWM
                reconky work
                ;;
        esac
        ;;

    *)
        xrandr --output HDMI1 --off --output LVDS1 --mode 1366x768 --pos 0x0 --rotate normal --output VIRTUAL1 --off --output DP1 --off --output VGA1 --off
        resetWM
        reconky
        ;;
esac
