#!/usr/bin/env zsh

if (pgrep "^trayer"); then
  killall trayer
else
  if [[ `hostname` = anaxagoras ]]; then
    exec trayer --edge right --tint black --transparent true --alpha 0 --SetPartialStrut true &
  else
    exec trayer --edge right --tint black --transparent true --alpha 0 --SetPartialStrut true&
  fi
fi
