#!/usr/bin/env ruby

info = `amixer -D pulse get Master`
toggle_command = "amixer -D pulse set Master "
status = info.split("\n").last.match(/.*\[(.*)\]$/)[1]

if status == "on"
    system toggle_command + "mute"
else
    system toggle_command + "unmute"
end
