#!/usr/bin/env bash

sink_name=`pactl list sinks short | grep analog-stereo | cut -f 2`

if [[ -z $1 ]]; then
    muted=`pactl -- list sinks | sed -e "/$sink_name/,/$sink_name/!d" | grep -E "Mute: .*" | sed -e "s/Mute: \(.*\)/\1/"`
    volume=`pactl -- list sinks | sed -e "/$sink_name/,/$sink_name/!d" | grep -E "^\s*Volume: .*" | cut -d / -f 2 | sed -r "s/\s*(.*)%\s*/\1/"`
    # echo $muted
    echo $volume
    # muted=`pactl -- list sinks | sed -e "/$sink_name/,/$sink_name/!d" | grep -E "Mute: .*" | sed -e "s/Mute: \(.*\)/\1/"`
    # if (echo $muted | grep "yes" > /dev/null); then
    # muted=`pactl -- list sinks | sed -e "/$sink_name/,/$sink_name/!d" | grep -E "Mute: .*" | sed -e "s/Mute: \(.*\)/\1/"`
    #     echo "○"
    # else
    #     echo "●"
    # fi
    exit 0
elif (echo $1 | grep "^%$" > /dev/null); then
    pactl -- set-sink-mute $sink_name toggle
    exit 0
else
    pactl -- set-sink-volume $sink_name $1
    exit 0
fi

