#!/usr/bin/env bash
# show own global ip

site=http://seemyip.com/
# site=http://checkip.dyndns.org/

if (ping -c 1 checkip.dyndns.org 2&> /dev/null); then
  echo "\ "
else
  wget $site -U 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0' -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>' | head -1
fi
